### ISSUE TITLE
IDiscoveryClient.ShutdownAsync()

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Discovery#13]
This method doesn't contain much documentation, but I'm guessing that it unregisters any information in Eureka using the asynchronous .NET functionality. 

In my .NET Core services, I'm calling it as part of the application shutdown. 

```CS
appLifetime.ApplicationStopping.Register(() =>
{
    discoveryClient.ShutdownAsync();
});
```
Since it's a void method, I cannot wait for the call to finish before doing further cleanup. If the process terminates quickly, I'm very unsure what happens to any async infrastructure that is set up to handle the ShutdownAsync() call. Can things be torn down before the method gets around to being called? 

Could we get a `Task ShutdownAsync()` method as well? Then we have more control over things.

**Comment by dtillman** [comment]
@kimbell:
Thanks for pointing this out.. I have changed the signature to return a Task instead of void.

As a side note, when the Eureka client is created, the factory that creates it attempts to obtain a IApplicationLifetime from the service container and if it is found, it Registers the ShutdownAsync() call for you, so you should not have to do it.

The above signature change will be in the 1.1.0-RC3 build and in the final.

Dave
