### ISSUE TITLE
How to set random port when the netcore service in docker?

### ISSUE THREAD

**Issue by lc273734858** [SteeltoeOSS/Discovery#16]
How to set random port when the netcore service in docker?

**Comment by dtillman** [comment]
@lc273734858:

Thanks for the question... were sorry its taken so long to respond..  If you never figured out how to deal with this or for others looking for answers the following should be helpful.

We have found with the latest Microsoft docker tooling and docker for windows its pretty easy to deal with this by using docker-compose.

1. Add docker support to your Visual Studio project so that you have docker compose files for your project.
2. In the docker-compose.override.yml file, add the eureka server.  Below is a compose file for the Discovery Sample: https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/AspDotNetCore

----------------------
version: '3'

services:
  fortune-teller-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  fortune-teller-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  eureka:
    image: steeltoeoss/servers:eurekaserver1.0-linux
    ports:
      - "8761:8761"
---------------

3. In your appsettings.json file, instead of using http://localhost:8761/eureka/ for the eureka server serviceUrl, use http://eureka:8761/eureka/ .  Note that the host name should match the service name from your compose file shown above (i.e. "eureka").

4. Have any services register with Eureka and startup listening on port 80.  e.g. eureka:instance:port=80 or not configured... as that's the default
